
nim = input("Masukkan Nim Anda: ")
nama = input("Maukkan Nama Lengkap: ")
kelas = input("Masukkan Kelas Anda: ")
usia = input("Masukkan usia: ")
print ("================================")
print ("IDENTITAS MAHASISWA")
print ("================================")
print ("NIM Mahasiswa :",nim)
print ("Nama Lengkap :",nama)
print ("Kelas Saat Ini:",kelas)
print ("Usia Anda:",usia)
print ("================================")
